//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Person = newPersonTable("public", "person", "")

type personTable struct {
	postgres.Table

	// Columns
	ID   postgres.ColumnString
	Name postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PersonTable struct {
	personTable

	EXCLUDED personTable
}

// AS creates new PersonTable with assigned alias
func (a PersonTable) AS(alias string) *PersonTable {
	return newPersonTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PersonTable with assigned schema name
func (a PersonTable) FromSchema(schemaName string) *PersonTable {
	return newPersonTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PersonTable with assigned table prefix
func (a PersonTable) WithPrefix(prefix string) *PersonTable {
	return newPersonTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PersonTable with assigned table suffix
func (a PersonTable) WithSuffix(suffix string) *PersonTable {
	return newPersonTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPersonTable(schemaName, tableName, alias string) *PersonTable {
	return &PersonTable{
		personTable: newPersonTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newPersonTableImpl("", "excluded", ""),
	}
}

func newPersonTableImpl(schemaName, tableName, alias string) personTable {
	var (
		IDColumn       = postgres.StringColumn("id")
		NameColumn     = postgres.StringColumn("name")
		allColumns     = postgres.ColumnList{IDColumn, NameColumn}
		mutableColumns = postgres.ColumnList{NameColumn}
	)

	return personTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:   IDColumn,
		Name: NameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
