// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/v1nidev/auge-service/ent/emergencycontact"
	"github.com/v1nidev/auge-service/ent/predicate"
)

// EmergencyContactDelete is the builder for deleting a EmergencyContact entity.
type EmergencyContactDelete struct {
	config
	hooks    []Hook
	mutation *EmergencyContactMutation
}

// Where appends a list predicates to the EmergencyContactDelete builder.
func (ecd *EmergencyContactDelete) Where(ps ...predicate.EmergencyContact) *EmergencyContactDelete {
	ecd.mutation.Where(ps...)
	return ecd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ecd *EmergencyContactDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ecd.sqlExec, ecd.mutation, ecd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ecd *EmergencyContactDelete) ExecX(ctx context.Context) int {
	n, err := ecd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ecd *EmergencyContactDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(emergencycontact.Table, sqlgraph.NewFieldSpec(emergencycontact.FieldID, field.TypeInt))
	if ps := ecd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ecd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ecd.mutation.done = true
	return affected, err
}

// EmergencyContactDeleteOne is the builder for deleting a single EmergencyContact entity.
type EmergencyContactDeleteOne struct {
	ecd *EmergencyContactDelete
}

// Where appends a list predicates to the EmergencyContactDelete builder.
func (ecdo *EmergencyContactDeleteOne) Where(ps ...predicate.EmergencyContact) *EmergencyContactDeleteOne {
	ecdo.ecd.mutation.Where(ps...)
	return ecdo
}

// Exec executes the deletion query.
func (ecdo *EmergencyContactDeleteOne) Exec(ctx context.Context) error {
	n, err := ecdo.ecd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{emergencycontact.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ecdo *EmergencyContactDeleteOne) ExecX(ctx context.Context) {
	if err := ecdo.Exec(ctx); err != nil {
		panic(err)
	}
}
