// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/v1nidev/auge-service/ent/emergencycontact"
	"github.com/v1nidev/auge-service/ent/member"
	"github.com/v1nidev/auge-service/ent/predicate"
)

// EmergencyContactQuery is the builder for querying EmergencyContact entities.
type EmergencyContactQuery struct {
	config
	ctx          *QueryContext
	order        []emergencycontact.OrderOption
	inters       []Interceptor
	predicates   []predicate.EmergencyContact
	withReferrer *MemberQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EmergencyContactQuery builder.
func (ecq *EmergencyContactQuery) Where(ps ...predicate.EmergencyContact) *EmergencyContactQuery {
	ecq.predicates = append(ecq.predicates, ps...)
	return ecq
}

// Limit the number of records to be returned by this query.
func (ecq *EmergencyContactQuery) Limit(limit int) *EmergencyContactQuery {
	ecq.ctx.Limit = &limit
	return ecq
}

// Offset to start from.
func (ecq *EmergencyContactQuery) Offset(offset int) *EmergencyContactQuery {
	ecq.ctx.Offset = &offset
	return ecq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ecq *EmergencyContactQuery) Unique(unique bool) *EmergencyContactQuery {
	ecq.ctx.Unique = &unique
	return ecq
}

// Order specifies how the records should be ordered.
func (ecq *EmergencyContactQuery) Order(o ...emergencycontact.OrderOption) *EmergencyContactQuery {
	ecq.order = append(ecq.order, o...)
	return ecq
}

// QueryReferrer chains the current query on the "referrer" edge.
func (ecq *EmergencyContactQuery) QueryReferrer() *MemberQuery {
	query := (&MemberClient{config: ecq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ecq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ecq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(emergencycontact.Table, emergencycontact.FieldID, selector),
			sqlgraph.To(member.Table, member.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, emergencycontact.ReferrerTable, emergencycontact.ReferrerColumn),
		)
		fromU = sqlgraph.SetNeighbors(ecq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EmergencyContact entity from the query.
// Returns a *NotFoundError when no EmergencyContact was found.
func (ecq *EmergencyContactQuery) First(ctx context.Context) (*EmergencyContact, error) {
	nodes, err := ecq.Limit(1).All(setContextOp(ctx, ecq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{emergencycontact.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ecq *EmergencyContactQuery) FirstX(ctx context.Context) *EmergencyContact {
	node, err := ecq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EmergencyContact ID from the query.
// Returns a *NotFoundError when no EmergencyContact ID was found.
func (ecq *EmergencyContactQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ecq.Limit(1).IDs(setContextOp(ctx, ecq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{emergencycontact.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ecq *EmergencyContactQuery) FirstIDX(ctx context.Context) int {
	id, err := ecq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EmergencyContact entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EmergencyContact entity is found.
// Returns a *NotFoundError when no EmergencyContact entities are found.
func (ecq *EmergencyContactQuery) Only(ctx context.Context) (*EmergencyContact, error) {
	nodes, err := ecq.Limit(2).All(setContextOp(ctx, ecq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{emergencycontact.Label}
	default:
		return nil, &NotSingularError{emergencycontact.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ecq *EmergencyContactQuery) OnlyX(ctx context.Context) *EmergencyContact {
	node, err := ecq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EmergencyContact ID in the query.
// Returns a *NotSingularError when more than one EmergencyContact ID is found.
// Returns a *NotFoundError when no entities are found.
func (ecq *EmergencyContactQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ecq.Limit(2).IDs(setContextOp(ctx, ecq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{emergencycontact.Label}
	default:
		err = &NotSingularError{emergencycontact.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ecq *EmergencyContactQuery) OnlyIDX(ctx context.Context) int {
	id, err := ecq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EmergencyContacts.
func (ecq *EmergencyContactQuery) All(ctx context.Context) ([]*EmergencyContact, error) {
	ctx = setContextOp(ctx, ecq.ctx, "All")
	if err := ecq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EmergencyContact, *EmergencyContactQuery]()
	return withInterceptors[[]*EmergencyContact](ctx, ecq, qr, ecq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ecq *EmergencyContactQuery) AllX(ctx context.Context) []*EmergencyContact {
	nodes, err := ecq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EmergencyContact IDs.
func (ecq *EmergencyContactQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ecq.ctx.Unique == nil && ecq.path != nil {
		ecq.Unique(true)
	}
	ctx = setContextOp(ctx, ecq.ctx, "IDs")
	if err = ecq.Select(emergencycontact.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ecq *EmergencyContactQuery) IDsX(ctx context.Context) []int {
	ids, err := ecq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ecq *EmergencyContactQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ecq.ctx, "Count")
	if err := ecq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ecq, querierCount[*EmergencyContactQuery](), ecq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ecq *EmergencyContactQuery) CountX(ctx context.Context) int {
	count, err := ecq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ecq *EmergencyContactQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ecq.ctx, "Exist")
	switch _, err := ecq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ecq *EmergencyContactQuery) ExistX(ctx context.Context) bool {
	exist, err := ecq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EmergencyContactQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ecq *EmergencyContactQuery) Clone() *EmergencyContactQuery {
	if ecq == nil {
		return nil
	}
	return &EmergencyContactQuery{
		config:       ecq.config,
		ctx:          ecq.ctx.Clone(),
		order:        append([]emergencycontact.OrderOption{}, ecq.order...),
		inters:       append([]Interceptor{}, ecq.inters...),
		predicates:   append([]predicate.EmergencyContact{}, ecq.predicates...),
		withReferrer: ecq.withReferrer.Clone(),
		// clone intermediate query.
		sql:  ecq.sql.Clone(),
		path: ecq.path,
	}
}

// WithReferrer tells the query-builder to eager-load the nodes that are connected to
// the "referrer" edge. The optional arguments are used to configure the query builder of the edge.
func (ecq *EmergencyContactQuery) WithReferrer(opts ...func(*MemberQuery)) *EmergencyContactQuery {
	query := (&MemberClient{config: ecq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ecq.withReferrer = query
	return ecq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PhoneNumber string `json:"phone_number,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EmergencyContact.Query().
//		GroupBy(emergencycontact.FieldPhoneNumber).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ecq *EmergencyContactQuery) GroupBy(field string, fields ...string) *EmergencyContactGroupBy {
	ecq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EmergencyContactGroupBy{build: ecq}
	grbuild.flds = &ecq.ctx.Fields
	grbuild.label = emergencycontact.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PhoneNumber string `json:"phone_number,omitempty"`
//	}
//
//	client.EmergencyContact.Query().
//		Select(emergencycontact.FieldPhoneNumber).
//		Scan(ctx, &v)
func (ecq *EmergencyContactQuery) Select(fields ...string) *EmergencyContactSelect {
	ecq.ctx.Fields = append(ecq.ctx.Fields, fields...)
	sbuild := &EmergencyContactSelect{EmergencyContactQuery: ecq}
	sbuild.label = emergencycontact.Label
	sbuild.flds, sbuild.scan = &ecq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EmergencyContactSelect configured with the given aggregations.
func (ecq *EmergencyContactQuery) Aggregate(fns ...AggregateFunc) *EmergencyContactSelect {
	return ecq.Select().Aggregate(fns...)
}

func (ecq *EmergencyContactQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ecq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ecq); err != nil {
				return err
			}
		}
	}
	for _, f := range ecq.ctx.Fields {
		if !emergencycontact.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ecq.path != nil {
		prev, err := ecq.path(ctx)
		if err != nil {
			return err
		}
		ecq.sql = prev
	}
	return nil
}

func (ecq *EmergencyContactQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EmergencyContact, error) {
	var (
		nodes       = []*EmergencyContact{}
		withFKs     = ecq.withFKs
		_spec       = ecq.querySpec()
		loadedTypes = [1]bool{
			ecq.withReferrer != nil,
		}
	)
	if ecq.withReferrer != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, emergencycontact.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EmergencyContact).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EmergencyContact{config: ecq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ecq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ecq.withReferrer; query != nil {
		if err := ecq.loadReferrer(ctx, query, nodes, nil,
			func(n *EmergencyContact, e *Member) { n.Edges.Referrer = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ecq *EmergencyContactQuery) loadReferrer(ctx context.Context, query *MemberQuery, nodes []*EmergencyContact, init func(*EmergencyContact), assign func(*EmergencyContact, *Member)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*EmergencyContact)
	for i := range nodes {
		if nodes[i].member_emergencycontact == nil {
			continue
		}
		fk := *nodes[i].member_emergencycontact
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(member.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "member_emergencycontact" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ecq *EmergencyContactQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ecq.querySpec()
	_spec.Node.Columns = ecq.ctx.Fields
	if len(ecq.ctx.Fields) > 0 {
		_spec.Unique = ecq.ctx.Unique != nil && *ecq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ecq.driver, _spec)
}

func (ecq *EmergencyContactQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(emergencycontact.Table, emergencycontact.Columns, sqlgraph.NewFieldSpec(emergencycontact.FieldID, field.TypeInt))
	_spec.From = ecq.sql
	if unique := ecq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ecq.path != nil {
		_spec.Unique = true
	}
	if fields := ecq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emergencycontact.FieldID)
		for i := range fields {
			if fields[i] != emergencycontact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ecq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ecq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ecq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ecq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ecq *EmergencyContactQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ecq.driver.Dialect())
	t1 := builder.Table(emergencycontact.Table)
	columns := ecq.ctx.Fields
	if len(columns) == 0 {
		columns = emergencycontact.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ecq.sql != nil {
		selector = ecq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ecq.ctx.Unique != nil && *ecq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ecq.predicates {
		p(selector)
	}
	for _, p := range ecq.order {
		p(selector)
	}
	if offset := ecq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ecq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EmergencyContactGroupBy is the group-by builder for EmergencyContact entities.
type EmergencyContactGroupBy struct {
	selector
	build *EmergencyContactQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ecgb *EmergencyContactGroupBy) Aggregate(fns ...AggregateFunc) *EmergencyContactGroupBy {
	ecgb.fns = append(ecgb.fns, fns...)
	return ecgb
}

// Scan applies the selector query and scans the result into the given value.
func (ecgb *EmergencyContactGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ecgb.build.ctx, "GroupBy")
	if err := ecgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EmergencyContactQuery, *EmergencyContactGroupBy](ctx, ecgb.build, ecgb, ecgb.build.inters, v)
}

func (ecgb *EmergencyContactGroupBy) sqlScan(ctx context.Context, root *EmergencyContactQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ecgb.fns))
	for _, fn := range ecgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ecgb.flds)+len(ecgb.fns))
		for _, f := range *ecgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ecgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ecgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EmergencyContactSelect is the builder for selecting fields of EmergencyContact entities.
type EmergencyContactSelect struct {
	*EmergencyContactQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ecs *EmergencyContactSelect) Aggregate(fns ...AggregateFunc) *EmergencyContactSelect {
	ecs.fns = append(ecs.fns, fns...)
	return ecs
}

// Scan applies the selector query and scans the result into the given value.
func (ecs *EmergencyContactSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ecs.ctx, "Select")
	if err := ecs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EmergencyContactQuery, *EmergencyContactSelect](ctx, ecs.EmergencyContactQuery, ecs, ecs.inters, v)
}

func (ecs *EmergencyContactSelect) sqlScan(ctx context.Context, root *EmergencyContactQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ecs.fns))
	for _, fn := range ecs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ecs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ecs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
