// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/v1nidev/auge-service/ent/emergencycontact"
	"github.com/v1nidev/auge-service/ent/member"
)

// EmergencyContactCreate is the builder for creating a EmergencyContact entity.
type EmergencyContactCreate struct {
	config
	mutation *EmergencyContactMutation
	hooks    []Hook
}

// SetPhoneNumber sets the "phone_number" field.
func (ecc *EmergencyContactCreate) SetPhoneNumber(s string) *EmergencyContactCreate {
	ecc.mutation.SetPhoneNumber(s)
	return ecc
}

// SetContactName sets the "contact_name" field.
func (ecc *EmergencyContactCreate) SetContactName(s string) *EmergencyContactCreate {
	ecc.mutation.SetContactName(s)
	return ecc
}

// SetReferrerID sets the "referrer" edge to the Member entity by ID.
func (ecc *EmergencyContactCreate) SetReferrerID(id int) *EmergencyContactCreate {
	ecc.mutation.SetReferrerID(id)
	return ecc
}

// SetReferrer sets the "referrer" edge to the Member entity.
func (ecc *EmergencyContactCreate) SetReferrer(m *Member) *EmergencyContactCreate {
	return ecc.SetReferrerID(m.ID)
}

// Mutation returns the EmergencyContactMutation object of the builder.
func (ecc *EmergencyContactCreate) Mutation() *EmergencyContactMutation {
	return ecc.mutation
}

// Save creates the EmergencyContact in the database.
func (ecc *EmergencyContactCreate) Save(ctx context.Context) (*EmergencyContact, error) {
	return withHooks(ctx, ecc.sqlSave, ecc.mutation, ecc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ecc *EmergencyContactCreate) SaveX(ctx context.Context) *EmergencyContact {
	v, err := ecc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecc *EmergencyContactCreate) Exec(ctx context.Context) error {
	_, err := ecc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecc *EmergencyContactCreate) ExecX(ctx context.Context) {
	if err := ecc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ecc *EmergencyContactCreate) check() error {
	if _, ok := ecc.mutation.PhoneNumber(); !ok {
		return &ValidationError{Name: "phone_number", err: errors.New(`ent: missing required field "EmergencyContact.phone_number"`)}
	}
	if v, ok := ecc.mutation.PhoneNumber(); ok {
		if err := emergencycontact.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phone_number", err: fmt.Errorf(`ent: validator failed for field "EmergencyContact.phone_number": %w`, err)}
		}
	}
	if _, ok := ecc.mutation.ContactName(); !ok {
		return &ValidationError{Name: "contact_name", err: errors.New(`ent: missing required field "EmergencyContact.contact_name"`)}
	}
	if _, ok := ecc.mutation.ReferrerID(); !ok {
		return &ValidationError{Name: "referrer", err: errors.New(`ent: missing required edge "EmergencyContact.referrer"`)}
	}
	return nil
}

func (ecc *EmergencyContactCreate) sqlSave(ctx context.Context) (*EmergencyContact, error) {
	if err := ecc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ecc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ecc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ecc.mutation.id = &_node.ID
	ecc.mutation.done = true
	return _node, nil
}

func (ecc *EmergencyContactCreate) createSpec() (*EmergencyContact, *sqlgraph.CreateSpec) {
	var (
		_node = &EmergencyContact{config: ecc.config}
		_spec = sqlgraph.NewCreateSpec(emergencycontact.Table, sqlgraph.NewFieldSpec(emergencycontact.FieldID, field.TypeInt))
	)
	if value, ok := ecc.mutation.PhoneNumber(); ok {
		_spec.SetField(emergencycontact.FieldPhoneNumber, field.TypeString, value)
		_node.PhoneNumber = value
	}
	if value, ok := ecc.mutation.ContactName(); ok {
		_spec.SetField(emergencycontact.FieldContactName, field.TypeString, value)
		_node.ContactName = value
	}
	if nodes := ecc.mutation.ReferrerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   emergencycontact.ReferrerTable,
			Columns: []string{emergencycontact.ReferrerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.member_emergencycontact = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EmergencyContactCreateBulk is the builder for creating many EmergencyContact entities in bulk.
type EmergencyContactCreateBulk struct {
	config
	err      error
	builders []*EmergencyContactCreate
}

// Save creates the EmergencyContact entities in the database.
func (eccb *EmergencyContactCreateBulk) Save(ctx context.Context) ([]*EmergencyContact, error) {
	if eccb.err != nil {
		return nil, eccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(eccb.builders))
	nodes := make([]*EmergencyContact, len(eccb.builders))
	mutators := make([]Mutator, len(eccb.builders))
	for i := range eccb.builders {
		func(i int, root context.Context) {
			builder := eccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmergencyContactMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, eccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, eccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, eccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (eccb *EmergencyContactCreateBulk) SaveX(ctx context.Context) []*EmergencyContact {
	v, err := eccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (eccb *EmergencyContactCreateBulk) Exec(ctx context.Context) error {
	_, err := eccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eccb *EmergencyContactCreateBulk) ExecX(ctx context.Context) {
	if err := eccb.Exec(ctx); err != nil {
		panic(err)
	}
}
