// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// EmergencyContact is the predicate function for emergencycontact builders.
type EmergencyContact func(*sql.Selector)

// Member is the predicate function for member builders.
type Member func(*sql.Selector)
